#!/bin/bash

# https://github.com/vivien/i3blocks-contrib/blob/master/iface/iface

IF="${IFACE:-$BLOCK_INSTANCE}"
IF="${IF:-$(ip route | awk '/^default/ { print $5 ; exit }')}"

[[ -z "$IF" ]] && exit
[[ ! -d /sys/class/net/${IF} ]] && exit

AF=${ADDRESS_FAMILY:-inet6?}
LABEL="${LABEL:-}"

for flag in "$1" "$2"; do
  case "$flag" in
    -4)
      AF=inet ;;
    -6)
      AF=inet6 ;;
    -L)
      if [[ "$IF" = "" ]]; then
        LABEL="iface"
      else
        LABEL="$IF:"
      fi ;;
  esac
done

if [[ "$IF" = "" ]] || [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo "${LABEL} down"
  echo "${LABEL} down"
  echo \#FF0000
  exit
fi

IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^ \/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

if [[ "${display_wifi_name}" == "1" ]];
then
  if command -v iw > /dev/null && iw $IF info > /dev/null 2>&1;
  then
    WIFI_NAME=$(iw $IF info | grep -Po '(?<=ssid ).*' | tr -d " \t\n\r")

    if [[ $BLOCK_BUTTON -eq 1 ]];
    then
      message="$LABEL $WIFI_NAME ($IPADDR)"
    else
      message="$LABEL $WIFI_NAME"
    fi
  else
    message="$LABEL $IPADDR"
  fi
else
  message="$LABEL $IPADDR"
fi

echo "$message"
